ALTER TABLE "User" ADD COLUMN "displayName" TEXT;
ALTER TABLE "User" ADD COLUMN "statusText" TEXT NOT NULL DEFAULT 'Online';
ALTER TABLE "User" ADD COLUMN "favoriteTrack" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "accentColor" TEXT NOT NULL DEFAULT '#7c5cff';
